# Generated by Django 3.0.4 on 2020-08-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problemId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('contestId', models.CharField(max_length=100)),
                ('index', models.CharField(max_length=100)),
                ('problemName', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('solvedCount', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ladder.Category')),
            ],
        ),
    ]
